<div class="container">
        <div class="row">

            <?php

            echo "<h1>Mes projets : ".$user->identite."</h1>";

            echo "<br>";



            //echo $projects->nom;
            for($i = 0; $i < count($projects); $i++) {
                echo $projects[$i]->nom;
                echo "<br>";
            }

            echo "<br>";

            echo $q['btOpen'];

            ?>

        </div>
    </div>
<?=$script_foot?>