<div class="container">
        <div class="row">

            <?php

            echo "<h1>Mes projets : ".$user->identite."</h1>";

            echo "<br>";

            for($i = 0; $i < count($projects); $i++) {
                $joursRest = (strtotime($projects[$i]->dateFinPrevue) - strtotime($projects[$i]->dateLancement)) / (60 * 60 * 24);
                echo "<br>";
                echo $projects[$i]->nom." nombre de jours restant : ".$joursRest;
                echo "<br>";
            }

            echo "<br>";

            //affiche la date d'aujourd'hui
            //$dateNow = date("j F Y", strtotime("now"));


            echo "<br>";

            echo $q['btOpen'];

            ?>

        </div>
    </div>
<?=$script_foot?>